pipeline:
  agent:
    any
  stages:
    - stage: Install
      steps:
        - sh 'npm install'
    - stage: Build
      steps:
        - sh 'sls package'
    - stage: Deploy
      steps:
        - sh 'sls deploy'

