service: my-serverless-app
provider:
  name: aws
  runtime: nodejs14.x
plugins:
  - serverless-offline
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: hello
          method: get
      - http:
          path: goodbye
          method: get

